apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "greeter-deployment"
  namespace: "default"
  labels:
    deployment: "greeter-deployment"
spec:
  replicas: 3
  # # minReadySeconds: 5
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  selector:
    matchLabels:
      pod: "greeter-pod"
  template:
    metadata:
      labels:
        pod: "greeter-pod"
    spec:
      # terminationGracePeriodSeconds: 30
      containers:
      - name: "greeter-app"
        image: "esuminski/english:fixed"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080