grafana:
    namespaceOverride: "default"
    grafana.ini:
      server:
        serve_from_sub_path: "true"
        root_url: "%(protocol)s://%(domain)s:/grafana/" # this lets Kubernetes auto set root_url value

    ingress:
      enabled: true
      path: /grafana
      ingressClassName: nginx