apiVersion: v1 # version of kubernetes you are writing
kind: Pod # type of kubernetes object you are creating
metadata: # information about the pod for kubernetes
  name: pod-name # this is needed for referencing the pod
  labels: # the labels are just for marking up and selecting pods
    app: app-name
    # can do more: they are really just key value pairs you can create
spec: # technical specifications of the pod
  containers:
    - name: application-name # arbitrary name
      image: image-information
      ports:
      - containerPort: 0000 # port number the app in the container listens on